# Generated by Django 5.0.6 on 2024-06-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_myprice_iscompletedproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprice',
            name='amry',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='myprice',
            name='armtek',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='myprice',
            name='carreta',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='myprice',
            name='emex',
            field=models.FloatField(default=0),
        ),
    ]
