# Generated by Django 5.0.6 on 2024-06-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_myprice_amry_myprice_armtek_myprice_carreta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprice',
            name='send',
            field=models.BooleanField(default=False),
        ),
    ]
