# Generated by Django 5.0.6 on 2024-06-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_myprice_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprice',
            name='page',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
