# Generated by Django 5.0.6 on 2024-07-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_myprice_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprice',
            name='amry_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myprice',
            name='armtek_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myprice',
            name='emex_done',
            field=models.BooleanField(default=False),
        ),
    ]
