# Generated by Django 5.0.6 on 2024-06-11 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPrice',
            fields=[
                ('detail', models.CharField()),
                ('brand', models.CharField()),
                ('article', models.CharField(primary_key=True, serialize=False)),
                ('buyPrice', models.FloatField()),
                ('salePrice', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='IsCompletedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('detail_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.myprice')),
            ],
        ),
    ]
